### ISSUE TITLE
能否讲解一下option_prefix 参数的使用场景？

### ISSUE THREAD

**Issue by busyfree** [bilibili/twirp#4]

**Comment by taoso** [comment]
twirp 的 hook 是 service 一级的，有的时候会不太灵活。

假设我们有 check_login, check_admin 两个 hook，假设我们有一个 comment 服务。
```proto
service Comment {
  rpc Get();
  rpc Create();
  rpc Update();
  rpc Delete();
}
```

查看评论不需要登录态，用户可以创建和更新评论但不能删除，管理员可以删除。

如何实现这种效果呢？
- 一种办法是在 hook 中根据当前接口的路径决定执行哪些检查。这样做需要在加方法的时候修改 hook 代码。
- 另一种办法是不用 hook，在各个方法里写代码做检查，这个就更不好用了。

---
option_prefix 为大家提供了另外一种选择。
```proto
service Comment {
  rpc Get();
  rpc Create(); // sniper:login
  rpc Update(); // sniper:login
  rpc Delete(); // sniper:admin
}
```
生成代码的时候设置 option_prefix 参数，框架会在处理请求的时候将 login 或 admin 注入到 ctx。各 hook 可以根据 ctx 中的取值决定是否执行相应的检查。

简单来说就是为各 hook 做一个编号，你可以在声明方法的时候指定要执行哪些 hook。

---
第一个版本是想用 proto 的 option 机制实现，只能传整数。但在使用过种只遇到了一些问题，没有解决。而且自定义 extension 的话 proto 导入路径也就个很麻烦的事情，就改成了现在这个样子。
